Add logic for enabling the CPU entitlement plugin to the appropriate …
cloudfoundry/docs-cf-admin pull request #220
Opened 2022-09-15 06:30 UTC by mmdacheva

…place

2022-09-15 06:41 UTC, sleepychild approved these changes
Looks ok.

2022-09-15 16:04 UTC, ameowlia requested changes
Hi @mmdacheva , 

Thank you so much for submitting this. 

I know I left a lot of comments, but this is a confusing topic and I want to make sure readers can understand.

Besides the specific comments, I suggest doing another edit with the following thoughts in mind:

1. **Don't use "you" when you mean "the app"**. For example `The new metric shows the amount of CPU usage relative to your entitlement` should be `The new metric shows the amount of CPU usage relative to an app's entitlement`
2. **Remove "expectations"**. In a few places you say something like "Given X you may expect Y to happen, but actually it is Z". Depending on someone's background they may or may not expect Y. Remove the ambiguity and say "When X then Z".
4. Shorter sentences are better.
5. Make sure the paragraphs are under the appropriate heading. 
6. Make sure each heading has a nice intro sentence to what the heading is for.

🙏 Again, I know I am asking a lot. Thank you so, so much for taking on this work.
Amelia

2022-09-15 16:04 UTC, ameowlia commented on using-cpu-entitlement-plugin.html.md.erb
> +[CPU Entitlements in Cloud Foundry](https://www.youtube.com/watch?v=vV87xmxKLeA)
I find it awkward that this link is here with no context. Maybe add it to the end with something like "if you more details", etc.

2022-09-15 16:04 UTC, ameowlia commented on using-cpu-entitlement-plugin.html.md.erb
> +CPU entitlement describes the percentage of host CPU a particular application instance is ‘entitled’ to use. Users will see CPU performance of less than 100% when their usage is within their entitlem
```suggestion
CPU entitlement describes the percentage of host CPU a particular application instance is ‘entitled’ to use. Apps will have a CPU performance of 100% when They are using exactly the CPU they are entitled. Apps will have a CPU performance of less than 100% when their usage is less than their entitlement and greater than 100% when they are above their entitlement.
```

2022-09-15 16:04 UTC, ameowlia commented on using-cpu-entitlement-plugin.html.md.erb
> +The property currently used to calculate CPU entitlement for metric purposes and for triggering moving between bad/good cgroups and its calculation is:
```suggestion
The equation used to calculate CPU entitlement is:
```

❓ Is there an equation to calculate CPU entitlement for other cases? This sentence makes it sound like there is?

2022-09-15 16:04 UTC, ameowlia commented on using-cpu-entitlement-plugin.html.md.erb
> +The new metric shows the amount of CPU usage relative to your entitlement.
```suggestion
The metric `AbsoluteCPUEntitlement` shows the amount of CPU usage relative to your entitlement. 
```

2022-09-15 16:04 UTC, ameowlia commented on using-cpu-entitlement-plugin.html.md.erb
> +To enable the CPU entitlement plugin, the field [experimental_cpu_throttling](https://github.com/cloudfoundry/garden-runc-release/blob/9d9826d08b72c0d8b7a7d968b1311047039be08c/jobs/garden/spec#L225-L
Can you add this to the numbered list above? I find it off that this requirement for the bosh deployment is _after_ "run the cf command".

2022-09-15 16:04 UTC, ameowlia commented on using-cpu-entitlement-plugin.html.md.erb
> +The exact mapping from memory to CPU is determined by the platform operator through a bosh release property on the garden release called [experimental_cpu_entitlement_per_share_in_percent](https://gi
This doesn't seem related to this section of "CPU Entitlement Plugin". 

Above it seems like it is always a 50% relationship. This makes it seem like that is not true. 

Can you move this closer to this section since it seems related: "The amount of CPU an application is entitled to is set proportionally to the amount of memory that the application has. For example, an application with access to 256MB of memory on a 512MB machine has access to half of the memory on the machine and is also entitled to half of the CPU of that machine."

2022-09-15 16:04 UTC, ameowlia commented on using-cpu-entitlement-plugin.html.md.erb
> +Entitlement is adjusted when [cpu-entitlement-per-share](https://github.com/cloudfoundry/garden-runc-release/blob/9d9826d08b72c0d8b7a7d968b1311047039be08c/jobs/garden/spec#L165-L167) is modified in t
This also seems like it is in the wrong section since it is not about using the CLI itself. 

Also I can't follow what you are trying to say here.  From this wording I can't tell what type of value this property is. I also find the wording "would expect" confusing; is that what happens or not? Can you also add an explanation about why someone would want to set this value?

2022-09-15 16:04 UTC, ameowlia commented on using-cpu-entitlement-plugin.html.md.erb
> +Imagine there are 3 cores on the Diego cell where your application is deployed to. That results in 300% CPU that will be distributed between all the applications on the cell, and this is the percenta
> and this is the percentage that the `cf app` command displays.

This makes it sound like `cf app` would display "300%". Is that the case?

2022-09-15 16:04 UTC, ameowlia commented on using-cpu-entitlement-plugin.html.md.erb
> +On a standard system, you can expect always to be able to get 100% of your CPU no matter what other applications are on the cell. If there are spare resources on the machine you will be allowed to co
What is a "standard system"?

2022-09-15 16:04 UTC, ameowlia commented on using-cpu-entitlement-plugin.html.md.erb
> +On a standard system, you can expect always to be able to get 100% of your CPU no matter what other applications are on the cell. If there are spare resources on the machine you will be allowed to co
Is this what you mean?

```suggestion
On a standard system, an app can expect always to be able to get 100% of your CPU entitlement no matter what other applications are on the cell. If there are spare resources on the machine you will be allowed to consume over 100% CPU.
```

2022-09-15 16:04 UTC, ameowlia commented on using-cpu-entitlement-plugin.html.md.erb
> +Let’s see how the spare resources are distributed on the Diego cell. Assume your well-behaved application that consumes less than its entitlement most of the time. Since you are behaving so well you
I found this section confusing. Especially the wording "you expect to get the maximum amount of spare CPU resources". I recommend removing any references to expectations and just focus on what actually happens.

2022-09-15 16:04 UTC, ameowlia commented on using-cpu-entitlement-plugin.html.md.erb
> +Current versions of Cloud Foundry allow applications to use more CPU than they are entitled to if CPU time is available at that moment, regardless of how the application has behaved in the past. This
In OS CF this option is already. It will be exposed in TAS 3.0. However, it is always configurable, so this won't change in the future without operator intervention.

2022-09-15 16:04 UTC, ameowlia commented on using-cpu-entitlement-plugin.html.md.erb
> +Both good and bad application always get their entitlement. The difference is in how the spare CPU gets distributed between them. All the spare CPU will be given to the good application that needs it
Only true if the feature is enabled.

2022-09-19 11:54 UTC, mmdacheva commented on using-cpu-entitlement-plugin.html.md.erb
> +Imagine there are 3 cores on the Diego cell where your application is deployed to. That results in 300% CPU that will be distributed between all the applications on the cell, and this is the percenta
Yes, exactly. 

If you have 3 cores, this equals a total of 300% CPU and if you have only 1 application, the cf app APP_NAME command will display 300% CPU for it.

If you have 2 applications on the same setup (3 cores), the cf app command will show ~150% for each app.

2022-09-19 16:48 UTC, ameowlia commented
Hi @mmdacheva, thanks for making changes! Ping me when you are ready for another review.

2022-09-20 06:33 UTC, mmdacheva commented
I am ready with the changes. Thank you @ameowlia

2022-09-23 15:15 UTC, ameowlia requested changes
⭐ Thank you for making all of those changes. We're getting close!

Main changes requested:
* I want to make sure it is clear when something will "always" happen vs when something will happen if a certain property is set a certain way. I want to make sure the doc calls out explicitly what happens when a property is set one way vs another.
* You give a good description of how to run the plugin in the "CPU Entitlement Plugin" section, but not what the output will actually look like or what to do with the output. You mention some of those details in later paragraphs, but I think it should be moved to the "CPU Entitlement Plugin" section.
* In one section you gave a great explanation about `experimental_cpu_entitlement_per_share_in_percent`. However, at the end of the doc you describe the effects of the `experimental_cpu_throttling` property, without talking about the two options very clearly. I would love if your explanation of `experimental_cpu_throttling` was formatted with examples the same way your great explanation of `experimental_cpu_entitlement_per_share_in_percent` is.

2022-09-23 15:15 UTC, ameowlia commented on using-cpu-entitlement-plugin.html.md.erb
> +If you wish to see an overview of the topic, please see the following video: [CPU Entitlements in Cloud Foundry](https://www.youtube.com/watch?v=vV87xmxKLeA)
```suggestion
If you wish to watch an overview of the topic, please see the following video: [CPU Entitlements in Cloud Foundry](https://www.youtube.com/watch?v=vV87xmxKLeA)
```

2022-09-23 15:15 UTC, ameowlia commented on using-cpu-entitlement-plugin.html.md.erb
> +CPU entitlement describes the percentage of host CPU a particular application instance is ‘entitled’ to use. Apps will have a CPU performance of 100% when They are using exactly the CPU they are enti
I wanted to differentiate this from what shows in `cf app APP`.

```suggestion
CPU entitlement describes the percentage of host CPU a particular application instance is ‘entitled’ to use. The CPU entitlement plugin will show that apps have a CPU performance of 100% when they are using exactly the CPU they are entitled. Apps will have a CPU performance of less than 100% when their usage is less than their entitlement and greater than 100% when they are above their entitlement.
```

2022-09-23 15:15 UTC, ameowlia commented on using-cpu-entitlement-plugin.html.md.erb
> +The amount of CPU an application is entitled to is set proportionally to the amount of memory that the application has. For example, an application with access to 256MB of memory on a 512MB machine h
Here I wanted to clarify that it is only like this example by default. In contrast to the paragraph below.

```suggestion
In Cloud Foundry the amount of CPU an application is entitled to is proportional to its allocated memory. By default, an application with access to 256MB of memory on a 512MB machine has access to half of the memory on the machine and is also entitled to half of the CPU of that machine. 
```

2022-09-23 15:15 UTC, ameowlia commented on using-cpu-entitlement-plugin.html.md.erb
> +The exact mapping from memory to CPU is determined by the platform operator through a bosh release property on the garden release called [experimental_cpu_entitlement_per_share_in_percent](https://gi
Getting rid of some passive voice.

```suggestion
An operator can change the exact mapping of memory to CPU by configuring the garden bosh release property called [`experimental_cpu_entitlement_per_share_in_percent`](https://github.com/cloudfoundry/garden-runc-release/blob/9d9826d08b72c0d8b7a7d968b1311047039be08c/jobs/garden/spec#L165-L167). This property changes the CPU percentage entitled to a container per CPU share. A value of 0.3 would mean that each application has access to 0.3% of the total CPU per share.
```

2022-09-23 15:15 UTC, ameowlia commented on using-cpu-entitlement-plugin.html.md.erb
> +By default the total shares available on a host is equal to the amount of memory on the host, an optimal value for experimental_cpu_entitlement_per_share_in_percent is 100% divided by the amount of t
```suggestion
By default the total shares available on a host is equal to the amount of memory on the host, an optimal value for `experimental_cpu_entitlement_per_share_in_percent` is 100% divided by the amount of total memory on the host. For example, a host with 1024MB of memory would have an optimal value of 100 / 1024, which is 0.0977% per share. An 256MB application would have access to 76.8% of the total CPU - in this case an operator has overcommitted on the amount of CPU available (assuming a single core machine).
```

2022-09-23 15:15 UTC, ameowlia commented on using-cpu-entitlement-plugin.html.md.erb
> +There are three possible states that emerge from how operators configure experimental_cpu_entitlement_per_share_in_percent:
```suggestion
There are three possible states that emerge from how operators configure `experimental_cpu_entitlement_per_share_in_percent`:
```

2022-09-23 15:15 UTC, ameowlia commented on using-cpu-entitlement-plugin.html.md.erb
> +The metric `AbsoluteCPUEntitlement` shows the amount of CPU usage relative to your entitlement.
```suggestion
The metric `AbsoluteCPUEntitlement` shows an app's CPU usage relative to an its entitlement. 
```

2022-09-23 15:15 UTC, ameowlia commented on using-cpu-entitlement-plugin.html.md.erb
> +2. Enable the CPU Entitlement plugin by setting the value for the field [experimental_cpu_throttling](https://github.com/cloudfoundry/garden-runc-release/blob/9d9826d08b72c0d8b7a7d968b1311047039be08c
This is confusing to me. That field doesn't actually _enable_ the CPU entitlement plugin, does it? That field just changes the throttling algorithm. 

❓ Do you have to have that property enabled to use the entitlement plugin or could you run the plugin without that property?

2022-09-23 15:15 UTC, ameowlia commented on using-cpu-entitlement-plugin.html.md.erb
> +This plugin allows Cloud Foundry application developers to make better decisions about scaling applications and initial resource allocation of applications.
You already have this overview at the top. I don't think you need it at the end. 

❓ Instead you can replace it with an example output of what a user would see and how to interpret it?

```suggestion
```

2022-09-23 15:15 UTC, ameowlia commented on using-cpu-entitlement-plugin.html.md.erb
> +An app can expect always to be able to get 100% of its CPU entitlement no matter what other applications are on the cell. If there are spare resources on the machine you will be allowed to consume ov
Is this true? What if the cell was overcommitted like you explained above?

2022-09-23 15:15 UTC, ameowlia commented on using-cpu-entitlement-plugin.html.md.erb
> +Let’s see how the spare resources are distributed on the Diego cell. Assume your well-behaved application that consumes less than its entitlement most of the time. Since your apps are behaving so wel
Can you split this paragraph into two paragraphs? One where `experimental_cpu_throttling` is set to true and one where it is set to false?

2022-09-23 15:15 UTC, ameowlia commented on using-cpu-entitlement-plugin.html.md.erb
> +When using the `cf cpu-entitlement` command you see 2 values - average and current usage. The average usage is used to split the application into 2 groups - good and bad. Good applications are the on
This seems like a good explanation to add to the bottom of the "CPU Entitlement plugin" section.

2022-09-23 15:15 UTC, ameowlia commented on using-cpu-entitlement-plugin.html.md.erb
> +Applications are allowed to temporarily exceed their entitlement, but preference are given to those applications that have been using less than their entitlement over a rolling window of time. Applic
Maybe combine this section with the "Spare CPU resources" section?

Given that this is only true when `experimental_cpu_throttling` is enabled, this paragraph seems more suited with the section explaining `experimental_cpu_throttling`.

2022-09-23 15:15 UTC, ameowlia commented on using-cpu-entitlement-plugin.html.md.erb
> +If the CPU spike of a good app is for a long period of time then it will eventually become a bad app and therefore will be throttled to 100% if a different good app needs the CPU. This way resources
Again I think this can all be combined with the section above when describing the two options for `experimental_cpu_throttling`

2022-09-23 15:15 UTC, ameowlia commented on using-cpu-entitlement-plugin.html.md.erb
> +2. Enable the CPU Entitlement plugin by setting the value for the field [experimental_cpu_throttling](https://github.com/cloudfoundry/garden-runc-release/blob/9d9826d08b72c0d8b7a7d968b1311047039be08c
```suggestion
2. Enable the CPU Entitlement plugin by setting the value for the field [`experimental_cpu_throttling`](https://github.com/cloudfoundry/garden-runc-release/blob/9d9826d08b72c0d8b7a7d968b1311047039be08c/jobs/garden/spec#L225-L227) to true by using this [operation](https://github.com/cloudfoundry/cf-deployment/blob/main/operations/enable-cpu-throttling.yml#L4)
```

2022-09-23 15:15 UTC, ameowlia commented on using-cpu-entitlement-plugin.html.md.erb
> +This topic describes how <%= vars.app_runtime_first %> admins can enable the CPU entitlement plugin to help them manage their CPU resources.
⭐ Yay! I love an intro sentence!

2022-09-23 15:15 UTC, ameowlia commented on using-cpu-entitlement-plugin.html.md.erb
> +
⭐ This is really great! I love the clear definition of terms and a table with examples!

2022-09-23 15:15 UTC, ameowlia commented on using-cpu-entitlement-plugin.html.md.erb
> +## <a id='cpu-entitlement'></a> CPU Entitlement plugin
```suggestion
## <a id='cpu-entitlement'></a> CPU Entitlement Plugin
```

2022-09-23 15:15 UTC, ameowlia commented on using-cpu-entitlement-plugin.html.md.erb
> +The exact mapping from memory to CPU is determined by the platform operator through a bosh release property on the garden release called [experimental_cpu_entitlement_per_share_in_percent](https://gi
⭐ I love the specific example here.

2022-09-28 13:11 UTC, mmdacheva commented on using-cpu-entitlement-plugin.html.md.erb
> +An app can expect always to be able to get 100% of its CPU entitlement no matter what other applications are on the cell. If there are spare resources on the machine you will be allowed to consume ov
This is what the [video](https://youtu.be/vV87xmxKLeA?t=183) regarding CPU entitlement says

2022-09-28 13:35 UTC, mmdacheva commented on using-cpu-entitlement-plugin.html.md.erb
> +Let’s see how the spare resources are distributed on the Diego cell. Assume your well-behaved application that consumes less than its entitlement most of the time. Since your apps are behaving so wel
The whole paragraph is explaining the situation when the `experimental_cpu_throttling` is set to flase.

2022-09-29 10:30 UTC, mmdacheva commented on using-cpu-entitlement-plugin.html.md.erb
> +2. Enable the CPU Entitlement plugin by setting the value for the field [experimental_cpu_throttling](https://github.com/cloudfoundry/garden-runc-release/blob/9d9826d08b72c0d8b7a7d968b1311047039be08c
Actually not, thank you for finding the mistake.

2022-09-30 15:31 UTC, merged